#!/usr/bin/env python3
"""Generate and validate the free-floating CubeSat with an SO-101 arm."""

from __future__ import annotations

import argparse
import difflib
import os
from collections.abc import Sequence
from pathlib import Path

import mujoco as mj
import numpy as np

MUJOCO_VERSION = "3.11.0"
SO101_MASS = 0.644006  # [kg], including the 12 g camera mount geom.
ACTUATOR_TORQUE_LIMIT = 2.94  # [N*m]
DYNAMIC_TEST_TORQUE = 0.2  # [N*m]
DYNAMIC_TEST_DURATION = 2.0  # [s]
DYNAMIC_TEST_PULSE_DURATION = 0.5  # [s]
COM_DRIFT_TOLERANCE = 1e-5  # [m]

MODEL_DIR = Path(__file__).resolve().parent
BUS_XML_PATH = MODEL_DIR / "cubesat_bus.xml"
SO101_DIR = MODEL_DIR.parent / "robotstudio_so101"
SO101_XML_PATH = SO101_DIR / "so101.xml"
SO101_ASSET_DIR = SO101_DIR / "assets"
DEFAULT_OUTPUT_PATH = MODEL_DIR / "cubesat_so101.xml"

EXPECTED_BODY_NAMES = {
    "cubesat_bus",
    "so101_base",
    "so101_shoulder",
    "so101_upper_arm",
    "so101_lower_arm",
    "so101_wrist",
    "so101_gripper",
    "so101_camera_mount",
    "so101_moving_jaw_so101_v1",
}
JOINT_NAMES = (
    "shoulder_pan",
    "shoulder_lift",
    "elbow_flex",
    "wrist_flex",
    "wrist_roll",
    "gripper",
)
EXPECTED_ACTUATOR_NAMES = tuple(f"so101_{name}_motor" for name in JOINT_NAMES)
GENERATED_HEADER = """<!--
  Generated by build_model.py; do not edit this file directly.
  The attached SO-101 model is derived from MuJoCo Menagerie and is licensed
  under Apache-2.0. See ../robotstudio_so101/LICENSE.
-->
"""


def _positive_float(value: str) -> float:
    """Parse a strictly positive floating-point command-line value."""
    number = float(value)
    if not np.isfinite(number) or number <= 0.0:
        raise argparse.ArgumentTypeError("value must be finite and greater than zero")
    return number


def _finite_vector(values: Sequence[float], name: str) -> np.ndarray:
    """Return a finite NumPy vector or raise a user-facing error."""
    vector = np.asarray(values, dtype=float)
    if not np.isfinite(vector).all():
        raise ValueError(f"{name} must contain only finite values")
    return vector


def _uniform_box_inertia(mass: float, size: np.ndarray) -> np.ndarray:
    """Compute ``Ixx, Iyy, Izz, Ixy, Ixz, Iyz`` for a uniform box."""
    x, y, z = size
    scale = mass / 12.0
    return np.array(
        [
            scale * (y * y + z * z),
            scale * (x * x + z * z),
            scale * (x * x + y * y),
            0.0,
            0.0,
            0.0,
        ]
    )


def _validate_full_inertia(full_inertia: np.ndarray) -> None:
    """Require a symmetric positive-definite physical inertia tensor."""
    ixx, iyy, izz, ixy, ixz, iyz = full_inertia
    tensor = np.array(
        [
            [ixx, ixy, ixz],
            [ixy, iyy, iyz],
            [ixz, iyz, izz],
        ]
    )
    if not np.all(np.linalg.eigvalsh(tensor) > 0.0):
        raise ValueError("bus full inertia must be positive definite")


def _convert_to_torque_actuators(arm: mj.MjSpec) -> None:
    """Replace SO-101 position-servo behavior with direct joint torque input."""
    torque_range = np.array([-ACTUATOR_TORQUE_LIMIT, ACTUATOR_TORQUE_LIMIT])

    def configure(actuator: mj.MjsActuator) -> None:
        actuator.gaintype = mj.mjtGain.mjGAIN_FIXED
        actuator.gainprm[:] = 0.0
        actuator.gainprm[0] = 1.0
        actuator.biastype = mj.mjtBias.mjBIAS_NONE
        actuator.biasprm[:] = 0.0
        actuator.dyntype = mj.mjtDyn.mjDYN_NONE
        actuator.gear[:] = [1.0, 0.0, 0.0, 0.0, 0.0, 0.0]
        actuator.ctrllimited = mj.mjtLimited.mjLIMITED_TRUE
        actuator.ctrlrange[:] = torque_range
        actuator.forcelimited = mj.mjtLimited.mjLIMITED_TRUE
        actuator.forcerange[:] = torque_range

    # MjSpec materializes inherited actuator defaults in nested classes. Clear
    # all upstream classes so future actuators cannot inherit dormant servo gains.
    for default_name in (
        "so101",
        "visual",
        "collision",
        "collision_gripper",
        "collision_gripper_mesh",
        "sts3215",
    ):
        configure(arm.find_default(default_name).actuator)

    for actuator in arm.actuators:
        actuator.name = f"{actuator.name}_motor"
        configure(actuator)


def build_spec(args: argparse.Namespace, output_path: Path) -> mj.MjSpec:
    """Build the combined model specification from the bus and vendored arm."""
    bus_size = _finite_vector(args.bus_size, "bus size")
    bus_com = _finite_vector(args.bus_com, "bus center of mass")
    if np.any(bus_size <= 0.0):
        raise ValueError("bus dimensions must be greater than zero")

    full_inertia = (
        _uniform_box_inertia(args.bus_mass, bus_size)
        if args.bus_fullinertia is None
        else _finite_vector(args.bus_fullinertia, "bus full inertia")
    )
    _validate_full_inertia(full_inertia)

    mount_position = (
        np.array([0.0, 0.0, bus_size[2] / 2.0])
        if args.mount_pos is None
        else _finite_vector(args.mount_pos, "mount position")
    )
    mount_quaternion = _finite_vector(args.mount_quat, "mount quaternion")
    quaternion_norm = np.linalg.norm(mount_quaternion)
    if quaternion_norm == 0.0:
        raise ValueError("mount quaternion must be nonzero")
    mount_quaternion /= quaternion_norm

    combined = mj.MjSpec.from_file(str(BUS_XML_PATH))
    bus = combined.body("cubesat_bus")
    bus.mass = args.bus_mass
    bus.ipos = bus_com
    bus.fullinertia = full_inertia

    half_size = bus_size / 2.0
    combined.geom("cubesat_visual").size = half_size
    combined.geom("cubesat_collision").size = half_size
    bus.add_site(
        name="so101_mount",
        pos=mount_position,
        quat=mount_quaternion,
        size=[0.003, 0.0, 0.0],
        group=4,
        rgba=[1.0, 0.2, 0.2, 1.0],
    )
    mount_frame = bus.add_frame(
        name="so101_mount_frame",
        pos=mount_position,
        quat=mount_quaternion,
    )

    arm = mj.MjSpec.from_file(str(SO101_XML_PATH))
    _convert_to_torque_actuators(arm)
    arm.body("base").pos = [0.0, 0.0, 0.0]
    mount_frame.attach_body(arm.body("base"), "so101_", "")

    relative_mesh_dir = os.path.relpath(SO101_ASSET_DIR, output_path.parent)
    combined.compiler.meshdir = Path(relative_mesh_dir).as_posix()
    return combined


def _names(model: mj.MjModel, object_type: mj.mjtObj, count: int) -> set[str]:
    """Collect all nonempty names for one compiled MuJoCo object type."""
    return {
        name
        for index in range(count)
        if (name := mj.mj_id2name(model, object_type, index)) is not None
    }


def validate_structure(model: mj.MjModel, bus_mass: float) -> None:
    """Validate the stable model interface and torque-actuator semantics."""
    if (model.nbody, model.nq, model.nv, model.nu, model.nmesh) != (10, 13, 12, 6, 18):
        raise ValueError(
            "unexpected model dimensions: "
            f"nbody={model.nbody}, nq={model.nq}, nv={model.nv}, "
            f"nu={model.nu}, nmesh={model.nmesh}"
        )

    body_names = _names(model, mj.mjtObj.mjOBJ_BODY, model.nbody)
    if not EXPECTED_BODY_NAMES.issubset(body_names):
        raise ValueError(f"missing bodies: {sorted(EXPECTED_BODY_NAMES - body_names)}")

    actuator_names = _names(model, mj.mjtObj.mjOBJ_ACTUATOR, model.nu)
    if actuator_names != set(EXPECTED_ACTUATOR_NAMES):
        raise ValueError(f"unexpected actuators: {sorted(actuator_names)}")

    joint_types = np.asarray(model.jnt_type)
    if np.count_nonzero(joint_types == mj.mjtJoint.mjJNT_FREE) != 1:
        raise ValueError("combined model must contain exactly one free joint")

    expected_mass = bus_mass + SO101_MASS
    total_mass = mj.mj_getTotalmass(model)
    if not np.isclose(total_mass, expected_mass, atol=1e-9):
        raise ValueError(
            f"unexpected total mass {total_mass}; expected {expected_mass}"
        )

    expected_range = np.tile(
        [-ACTUATOR_TORQUE_LIMIT, ACTUATOR_TORQUE_LIMIT], (model.nu, 1)
    )
    if not np.allclose(model.actuator_ctrlrange, expected_range):
        raise ValueError("actuator control ranges are not the expected torque limits")
    if not np.allclose(model.actuator_forcerange, expected_range):
        raise ValueError("actuator force ranges are not the expected torque limits")
    if not np.allclose(model.actuator_gainprm[:, 0], 1.0):
        raise ValueError("torque actuators must use unit fixed gain")
    if not np.allclose(model.actuator_gainprm[:, 1:], 0.0):
        raise ValueError("torque actuators contain unexpected gain parameters")
    if not np.allclose(model.actuator_biasprm, 0.0):
        raise ValueError("torque actuators must not contain position-servo bias")
    if not np.allclose(model.actuator_gear[:, 0], 1.0):
        raise ValueError("torque actuators must use unit joint gear")
    if not np.allclose(model.actuator_gear[:, 1:], 0.0):
        raise ValueError("torque actuators contain unexpected gear components")
    if not np.all(model.actuator_trntype == mj.mjtTrn.mjTRN_JOINT):
        raise ValueError("all torque actuators must use joint transmission")
    if not np.all(model.actuator_dyntype == mj.mjtDyn.mjDYN_NONE):
        raise ValueError("torque actuators must not have activation dynamics")
    if not np.all(model.actuator_gaintype == mj.mjtGain.mjGAIN_FIXED):
        raise ValueError("torque actuators must use fixed gain")
    if not np.all(model.actuator_biastype == mj.mjtBias.mjBIAS_NONE):
        raise ValueError("torque actuators must not use actuator bias")

    for site_name in (
        "cubesat_origin",
        "so101_mount",
        "so101_baseframe",
        "so101_gripperframe",
    ):
        if mj.mj_name2id(model, mj.mjtObj.mjOBJ_SITE, site_name) < 0:
            raise ValueError(f"missing site {site_name}")
    if mj.mj_name2id(model, mj.mjtObj.mjOBJ_CAMERA, "so101_wrist_cam") < 0:
        raise ValueError("missing SO-101 wrist camera")

    data = mj.MjData(model)
    mj.mj_forward(model, data)
    if data.ncon != 0:
        raise ValueError(f"default configuration contains {data.ncon} contacts")


def validate_free_floating_response(model: mj.MjModel) -> None:
    """Check that an internal torque moves both the arm and free-floating bus."""
    data = mj.MjData(model)
    mj.mj_forward(model, data)
    initial_com = data.subtree_com[0].copy()
    initial_bus_pose = data.qpos[:7].copy()

    actuator_id = mj.mj_name2id(
        model, mj.mjtObj.mjOBJ_ACTUATOR, "so101_shoulder_lift_motor"
    )
    joint_id = mj.mj_name2id(model, mj.mjtObj.mjOBJ_JOINT, "so101_shoulder_lift")
    joint_qpos_address = model.jnt_qposadr[joint_id]
    steps = round(DYNAMIC_TEST_DURATION / model.opt.timestep)
    pulse_steps = round(DYNAMIC_TEST_PULSE_DURATION / model.opt.timestep)

    for step in range(steps):
        data.ctrl[actuator_id] = DYNAMIC_TEST_TORQUE if step < pulse_steps else 0.0
        mj.mj_step(model, data)
        if data.ncon != 0:
            raise ValueError("unexpected contact during free-floating response test")

    mj.mj_forward(model, data)
    if not np.isfinite(data.qpos).all() or not np.isfinite(data.qvel).all():
        raise ValueError("free-floating response produced non-finite state")
    if abs(data.qpos[joint_qpos_address]) <= 1e-3:
        raise ValueError("shoulder lift did not respond to the torque pulse")
    if np.linalg.norm(data.qpos[:7] - initial_bus_pose) <= 1e-5:
        raise ValueError("CubeSat bus did not exhibit arm reaction motion")
    com_drift = np.linalg.norm(data.subtree_com[0] - initial_com)
    if com_drift > COM_DRIFT_TOLERANCE:
        raise ValueError(
            f"system center-of-mass drift {com_drift} exceeds {COM_DRIFT_TOLERANCE}"
        )


def generate_xml(args: argparse.Namespace, output_path: Path) -> str:
    """Build, validate, and serialize the deterministic combined MJCF."""
    spec = build_spec(args, output_path)
    model = spec.compile()
    validate_structure(model, args.bus_mass)
    validate_free_floating_response(model)
    return GENERATED_HEADER + spec.to_xml()


def _parse_args() -> argparse.Namespace:
    """Parse the model generator command-line interface."""
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--bus-size",
        nargs=3,
        type=_positive_float,
        default=(0.2263, 0.2263, 0.3405),
        metavar=("X", "Y", "Z"),
        help="full CubeSat bus dimensions in meters",
    )
    parser.add_argument(
        "--bus-mass",
        type=_positive_float,
        default=24.0,
        help="CubeSat bus mass in kilograms",
    )
    parser.add_argument(
        "--bus-com",
        nargs=3,
        type=float,
        default=(0.0, 0.0, 0.0),
        metavar=("X", "Y", "Z"),
        help="bus center of mass in the bus frame, in meters",
    )
    parser.add_argument(
        "--bus-fullinertia",
        nargs=6,
        type=float,
        metavar=("IXX", "IYY", "IZZ", "IXY", "IXZ", "IYZ"),
        help="bus full inertia tensor in kg*m^2; defaults to a uniform box",
    )
    parser.add_argument(
        "--mount-pos",
        nargs=3,
        type=float,
        metavar=("X", "Y", "Z"),
        help="arm mount position in meters; defaults to the +Z face center",
    )
    parser.add_argument(
        "--mount-quat",
        nargs=4,
        type=float,
        default=(1.0, 0.0, 0.0, 0.0),
        metavar=("W", "X", "Y", "Z"),
        help="arm mount quaternion in MuJoCo w-x-y-z order",
    )
    parser.add_argument(
        "--output",
        type=Path,
        default=DEFAULT_OUTPUT_PATH,
        help="generated MJCF path",
    )
    parser.add_argument(
        "--check",
        action="store_true",
        help="verify that the existing output is current without rewriting it",
    )
    return parser.parse_args()


def main() -> int:
    """Run the model generator or its non-mutating consistency check."""
    args = _parse_args()
    if mj.__version__ != MUJOCO_VERSION:
        raise RuntimeError(
            f"model generation requires mujoco=={MUJOCO_VERSION}; found {mj.__version__}"
        )

    output_path = args.output.expanduser().resolve()
    if output_path == BUS_XML_PATH or SO101_DIR in output_path.parents:
        raise ValueError("output must not overwrite a source or vendored SO-101 file")
    if output_path.suffix.lower() != ".xml":
        raise ValueError("output path must use the .xml extension")
    generated_xml = generate_xml(args, output_path)

    if args.check:
        if not output_path.exists():
            raise FileNotFoundError(f"generated model does not exist: {output_path}")
        current_xml = output_path.read_text(encoding="utf-8")
        if current_xml != generated_xml:
            difference = "".join(
                difflib.unified_diff(
                    current_xml.splitlines(keepends=True),
                    generated_xml.splitlines(keepends=True),
                    fromfile=str(output_path),
                    tofile="regenerated",
                )
            )
            raise RuntimeError(f"generated model is out of date:\n{difference}")
        model = mj.MjModel.from_xml_path(str(output_path))
        validate_structure(model, args.bus_mass)
        validate_free_floating_response(model)
        print(f"Model is current and valid: {output_path}")
        return 0

    output_path.parent.mkdir(parents=True, exist_ok=True)
    output_path.write_text(generated_xml, encoding="utf-8")
    model = mj.MjModel.from_xml_path(str(output_path))
    validate_structure(model, args.bus_mass)
    validate_free_floating_response(model)
    print(f"Generated and validated: {output_path}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
