#!/usr/bin/env python3
"""Generate and validate the free-floating CubeSat grasp-test model."""

from __future__ import annotations

import argparse
import difflib
import os
from pathlib import Path

import mujoco as mj
import numpy as np

MUJOCO_VERSION = "3.11.0"
TARGET_MASS = 0.10  # [kg]
TARGET_COM = np.array([0.055, 0.0, 0.0])  # [m], in the target body frame.
TARGET_INERTIA = np.array([3.349333333e-5, 7.758e-5, 7.758e-5])  # [kg*m^2]
EXPECTED_TOTAL_MASS = 24.744006  # [kg]

MODEL_DIR = Path(__file__).resolve().parent
SOURCE_MODEL = MODEL_DIR.parent / "cubesat_so101" / "cubesat_so101.xml"
SO101_ASSET_DIR = MODEL_DIR.parent / "robotstudio_so101" / "assets"
DEFAULT_OUTPUT_PATH = MODEL_DIR / "cubesat_so101_grasp.xml"

GENERATED_HEADER = """<!--
  Generated by build_model.py; do not edit this file directly.
  The attached SO-101 model is derived from MuJoCo Menagerie and is licensed
  under Apache-2.0. See ../robotstudio_so101/LICENSE.
-->
"""


def build_spec(output_path: Path) -> mj.MjSpec:
    """Add an independent calibrated capture target to the combined model."""
    spec = mj.MjSpec.from_file(str(SOURCE_MODEL))
    target = spec.worldbody.add_body(
        name="capture_target",
        pos=[1.0, 0.0, 0.0],  # [m], contact-free storage pose.
    )
    target.add_freejoint(name="capture_target_free")
    target.mass = TARGET_MASS
    target.ipos = TARGET_COM
    target.iquat = [1.0, 0.0, 0.0, 0.0]
    target.inertia = TARGET_INERTIA
    target.explicitinertial = True

    target.add_geom(
        name="capture_target_handle",
        type=mj.mjtGeom.mjGEOM_CYLINDER,
        pos=[0.015, 0.0, 0.0],  # [m]
        quat=[0.707106781, 0.0, 0.707106781, 0.0],
        size=[0.004, 0.025, 0.0],  # [m], radius and half-length.
        mass=0.0,
        rgba=[0.85, 0.25, 0.12, 1.0],
        condim=6,
        priority=1,
        friction=[1.0, 0.005, 0.0005],
        solref=[0.01, 1.0],
    )
    target.add_geom(
        name="capture_target_body_geom",
        type=mj.mjtGeom.mjGEOM_BOX,
        pos=[0.065, 0.0, 0.0],  # [m]
        size=[0.025, 0.025, 0.025],  # [m], half-sizes.
        mass=0.0,
        rgba=[0.25, 0.45, 0.72, 1.0],
    )
    target.add_site(
        name="capture_target_grasp",
        pos=[0.015, 0.0, 0.0],  # [m]
        quat=[0.707106781, 0.0, 0.707106781, 0.0],
        type=mj.mjtGeom.mjGEOM_CYLINDER,
        size=[0.005, 0.026, 0.0],  # [m]
        group=4,
        rgba=[1.0, 0.8, 0.1, 0.5],
    )

    relative_mesh_dir = os.path.relpath(SO101_ASSET_DIR, output_path.parent)
    spec.compiler.meshdir = Path(relative_mesh_dir).as_posix()
    return spec


def _object_names(model: mj.MjModel, object_type: mj.mjtObj, count: int) -> set[str]:
    """Return all named objects of one MuJoCo type."""
    return {
        name
        for index in range(count)
        if (name := mj.mj_id2name(model, object_type, index)) is not None
    }


def validate_model(model: mj.MjModel) -> None:
    """Validate the target interface, physical properties, and default state."""
    expected = (11, 20, 18, 6, 18)
    actual = (model.nbody, model.nq, model.nv, model.nu, model.nmesh)
    if actual != expected:
        raise ValueError(f"unexpected model dimensions {actual}; expected {expected}")

    joint_types = np.asarray(model.jnt_type)
    if np.count_nonzero(joint_types == mj.mjtJoint.mjJNT_FREE) != 2:
        raise ValueError("grasp model must contain exactly two free joints")
    for name in ("capture_target", "capture_target_handle", "capture_target_body_geom"):
        names = _object_names(
            model,
            mj.mjtObj.mjOBJ_BODY if name == "capture_target" else mj.mjtObj.mjOBJ_GEOM,
            model.nbody if name == "capture_target" else model.ngeom,
        )
        if name not in names:
            raise ValueError(f"missing object {name}")
    if mj.mj_name2id(model, mj.mjtObj.mjOBJ_SITE, "capture_target_grasp") < 0:
        raise ValueError("missing site capture_target_grasp")
    if model.neq != 0:
        raise ValueError("pure-contact model must not contain equality constraints")
    if not np.isclose(mj.mj_getTotalmass(model), EXPECTED_TOTAL_MASS, atol=1e-9):
        raise ValueError("unexpected combined system mass")

    target_id = mj.mj_name2id(model, mj.mjtObj.mjOBJ_BODY, "capture_target")
    if not np.isclose(model.body_mass[target_id], TARGET_MASS, atol=1e-12):
        raise ValueError("unexpected target mass")
    if not np.allclose(model.body_ipos[target_id], TARGET_COM, atol=1e-12):
        raise ValueError("unexpected target center of mass")
    if not np.allclose(model.body_inertia[target_id], TARGET_INERTIA, atol=1e-12):
        raise ValueError("unexpected target inertia")
    if not np.all(model.body_inertia[target_id] > 0.0):
        raise ValueError("target inertia must be positive definite")

    handle_id = mj.mj_name2id(model, mj.mjtObj.mjOBJ_GEOM, "capture_target_handle")
    if model.geom_condim[handle_id] != 6 or model.geom_priority[handle_id] != 1:
        raise ValueError("unexpected handle contact dimensionality or priority")
    if not np.allclose(model.geom_friction[handle_id], [1.0, 0.005, 0.0005]):
        raise ValueError("unexpected handle friction")

    data = mj.MjData(model)
    mj.mj_forward(model, data)
    if data.ncon != 0:
        raise ValueError(f"default configuration contains {data.ncon} contacts")


def generate_xml(output_path: Path) -> str:
    """Build, validate, and serialize the deterministic grasp model."""
    spec = build_spec(output_path)
    validate_model(spec.compile())
    return GENERATED_HEADER + spec.to_xml()


def _parse_args() -> argparse.Namespace:
    """Parse command-line arguments."""
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--output", type=Path, default=DEFAULT_OUTPUT_PATH)
    parser.add_argument(
        "--check",
        action="store_true",
        help="verify that the existing output is current without rewriting it",
    )
    return parser.parse_args()


def main() -> int:
    """Generate the model or check its committed representation."""
    args = _parse_args()
    if mj.__version__ != MUJOCO_VERSION:
        raise RuntimeError(
            f"model generation requires mujoco=={MUJOCO_VERSION}; found {mj.__version__}"
        )
    output_path = args.output.expanduser().resolve()
    if output_path == SOURCE_MODEL or SO101_ASSET_DIR.parent in output_path.parents:
        raise ValueError("output must not overwrite source or vendored model files")
    if output_path.suffix.lower() != ".xml":
        raise ValueError("output path must use the .xml extension")

    generated_xml = generate_xml(output_path)
    if args.check:
        if not output_path.exists():
            raise FileNotFoundError(f"generated model does not exist: {output_path}")
        current_xml = output_path.read_text(encoding="utf-8")
        if current_xml != generated_xml:
            difference = "".join(
                difflib.unified_diff(
                    current_xml.splitlines(keepends=True),
                    generated_xml.splitlines(keepends=True),
                    fromfile=str(output_path),
                    tofile="regenerated",
                )
            )
            raise RuntimeError(f"generated model is out of date:\n{difference}")
        validate_model(mj.MjModel.from_xml_path(str(output_path)))
        print(f"Model is current and valid: {output_path}")
        return 0

    output_path.parent.mkdir(parents=True, exist_ok=True)
    output_path.write_text(generated_xml, encoding="utf-8")
    validate_model(mj.MjModel.from_xml_path(str(output_path)))
    print(f"Generated and validated: {output_path}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
